This seems to cause an error
Searching... (use --region to specify a region)
Traceback (most recent call last):
  File "./autodeploy.py", line 546, in <module>
    main()
  File "./autodeploy.py", line 537, in main
    instance = Instance(**kwargs)
  File "./autodeploy.py", line 112, in __init__
    if self.region:
AttributeError: Instance instance has no attribute 'region'

Revert "Be more consistent about self.region."

This reverts commit d8fb9d96d93503a9cd839fa0c342116473edfc5d.